[package]
name = "rederr"
version = "0.1.0"
authors = ["Daniel Parks <oss-rederr@demonhorse.org>"]
description = "Run a program, timestamp each line of output, and make stderr red"
homepage = "https://github.com/danielparks/rederr"
repository = "https://github.com/danielparks/rederr"
readme = "README.md"
keywords = []
categories = [] # https://crates.io/category_slugs
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0.44"
atty = "0.2.14"
clap = { version = "3.2.15", features = ["derive"] }
duration-str = "0.4.0"
nix = { version = "0.24.2", features = ["fs"] }
popol = "0.5.0"
termcolor = "1.1.3"
