[bans]
multiple-versions = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "MIT",
  "Unicode-DFS-2016",
  "Unlicense",
  "Zlib",
]
default = "deny"
unused-allowed-license = "allow"
